import type { QuizQuestion } from "@/components/quiz"

export const quizData: Record<string, QuizQuestion[]> = {
  "introduction-to-python": [
    {
      id: "intro-1",
      type: "multiple-choice",
      question: "Which function is used to display output in Python?",
      options: ["show()", "output()", "print()", "display()"],
      correctAnswer: 2,
      explanation: "Python uses print() to display output.",
    },
    {
      id: "intro-2",
      type: "multiple-choice",
      question: "What is the output of print(\"Hello\", \"World\")?",
      options: ["HelloWorld", "Hello World", '\"Hello\", \"World\"', "Error"],
      correctAnswer: 1,
      explanation: "By default, print separates values with a space.",
    },
    {
      id: "intro-3",
      type: "multiple-choice",
      question: "What will this code print?\\n\\nprint(\"Apple\", \"Banana\", sep=\"-\")",
      options: ["Apple Banana", "Apple-Banana", "Apple, Banana", "Error"],
      correctAnswer: 1,
      explanation: "sep=\"-\" joins values with -.",
    },
    {
      id: "intro-4",
      type: "multiple-choice",
      question: "What will be the output?\n\nprint(\"Good Morning\")",
      options: ["Good Morning", "GoodMorning", "Good morning", "Error"],
      correctAnswer: 2,
      explanation: "end=\" \" keeps both words on same line with a space.",
    },
    {
      id: "intro-5",
      type: "multiple-choice",
      question: "Which argument in print() is used to join multiple values with a symbol?",
      options: ["end", "sep", "join", "concat"],
      correctAnswer: 1,
      explanation: "sep defines separator.",
    },
  ],
  "syntax-variables-data-types": [
    {
      id: "syntax-1",
      type: "multiple-choice",
      question: "Which of these is a valid variable name?",
      options: ["1name", "my_name", "my-name", "@age"],
      correctAnswer: 1,
      explanation: "Variable names cannot start with numbers or use special symbols except _.",
    },
    {
      id: "syntax-2",
      type: "multiple-choice",
      question: "What is the output?\n\nx = 10\nx = 20\nprint(x)",
      options: ["10", "20", "30", "Error"],
      correctAnswer: 1,
      explanation: "Latest assignment updates the variable.",
    },
    {
      id: "syntax-3",
      type: "multiple-choice",
      question: "Which is NOT a rule for variable naming in Python?",
      options: ["Can use underscores (_)" , "Can start with number", "Cannot use symbols like @, #", "Can contain letters and numbers"],
      correctAnswer: 1,
      explanation: "Variables cannot start with numbers.",
    },
    {
      id: "syntax-4",
      type: "multiple-choice",
      question: "What is the output?\n\na, b = 5, 10\nprint(a, b)",
      options: ["5 10", "10 5", "Error", "(5,10)"],
      correctAnswer: 0,
      explanation: "Python supports multiple assignment.",
    },
    {
      id: "syntax-5",
      type: "multiple-choice",
      question: "What is stored in x after this code?\n\nx = \"School\"\nx = 25",
      options: ["School", "25", "Error", "Both values"],
      correctAnswer: 1,
      explanation: "New value (25) replaces old one.",
    },
    {
      id: "syntax-6",
      type: "multiple-choice",
      question: "Which of these is NOT a Python data type?",
      options: ["int", "float", "bool", "digit"],
      correctAnswer: 3,
      explanation: "Python has int, float, bool, but no digit type.",
    },
    {
      id: "syntax-7",
      type: "multiple-choice",
      question: "What is the output?\n\nprint(type(3.5))",
      options: ["<class 'int'>", "<class 'float'>", "<class 'decimal'>", "<class 'number'>"],
      correctAnswer: 1,
      explanation: "3.5 is a float.",
    },
    {
      id: "syntax-8",
      type: "multiple-choice",
      question: "Which of the following represents a boolean value?",
      options: ["True", "False", "1", "All of the above"],
      correctAnswer: 4,
      explanation: "Python True = 1, False = 0.",
    },
    {
      id: "syntax-9",
      type: "multiple-choice",
      question: "Which data type is used for text in Python?",
      options: ["int", "str", "text", "char"],
      correctAnswer: 1,
      explanation: "Python uses str (string).",
    },
    {
      id: "syntax-10",
      type: "multiple-choice",
      question: "What is the type of 2 + 3j in Python?",
      options: ["int", "float", "complex", "str"],
      correctAnswer: 2,
      explanation: "a+bj is a complex number.",
    },
  ],
  "operators-control-flow": [
    {
      id: "control-1",
      type: "multiple-choice",
      question: "What is the correct syntax of an if statement in Python?",
      options: ["if (x > 5):", "if x > 5", "if x > 5:", "if: x > 5"],
      correctAnswer: 2,
      explanation: "Python requires a colon (:) after if.",
    },
    {
      id: "control-2",
      type: "multiple-choice",
      question: "Which keyword is used for multiple conditions in Python?",
      options: ["elseif", "elif", "else if", "elseif()"],
      correctAnswer: 1,
      explanation: "Python uses elif for multiple conditions.",
    },
    {
      id: "control-3",
      type: "multiple-choice",
      question: "What will be the output?\n\nage = 20\nif age >= 18:\n    print(\"Adult\")\nelse:\n    print(\"Child\")",
      options: ["Adult", "Child", "20", "Error"],
      correctAnswer: 0,
      explanation: "Since 20 >= 18, “Adult” is printed.",
    },
    {
      id: "control-4",
      type: "multiple-choice",
      question: "What will this code print?\n\nmarks = 30\nif marks >= 40:\n    print(\"Pass\")\nelse:\n    print(\"Fail\")",
      options: ["Pass", "Fail", "Error", "Nothing"],
      correctAnswer: 1,
      explanation: "Condition is false, so else runs.",
    },
    {
      id: "control-5",
      type: "multiple-choice",
      question: "Which of the following is wrong in Python?",
      options: ["if x == 5:", "if x = 5:", "if x != 5:", "if x > 5:"],
      correctAnswer: 1,
      explanation: "= is assignment, not comparison. Use ==.",
    },
    {
      id: "control-6",
      type: "multiple-choice",
      question: "What will this code print?\n\nscore = 75\nif score >= 90:\n    print(\"Grade A\")\nelif score >= 60:\n    print(\"Grade B\")\nelse:\n    print(\"Grade C\")",
      options: ["Grade A", "Grade B", "Grade C", "Error"],
      correctAnswer: 1,
      explanation: "75 ≥ 60, but not ≥ 90, so Grade B.",
    },
    {
      id: "control-7",
      type: "multiple-choice",
      question: "Which keyword is used to handle “otherwise” condition?",
      options: ["elseif", "other", "else", "default"],
      correctAnswer: 2,
      explanation: "else is used when no condition matches.",
    },
  ],
  "loops-strings": [
    {
      id: "control-1",
      type: "multiple-choice",
      question: "What is the correct syntax of an if statement in Python?",
      options: ["if (x > 5):", "if x > 5", "if x > 5:", "if: x > 5"],
      correctAnswer: 2,
      explanation: "Python requires a colon (:) after if.",
    },
    {
      id: "control-2",
      type: "multiple-choice",
      question: "Which keyword is used for multiple conditions in Python?",
      options: ["elseif", "elif", "else if", "elseif()"],
      correctAnswer: 1,
      explanation: "Python uses elif for multiple conditions.",
    },
    {
      id: "control-3",
      type: "multiple-choice",
      question: "What will be the output?\n\nage = 20\nif age >= 18:\n    print(\"Adult\")\nelse:\n    print(\"Child\")",
      options: ["Adult", "Child", "20", "Error"],
      correctAnswer: 0,
      explanation: "Since 20 >= 18, “Adult” is printed.",
    },
    {
      id: "control-4",
      type: "multiple-choice",
      question: "What will this code print?\n\nmarks = 30\nif marks >= 40:\n    print(\"Pass\")\nelse:\n    print(\"Fail\")",
      options: ["Pass", "Fail", "Error", "Nothing"],
      correctAnswer: 1,
      explanation: "Condition is false, so else runs.",
    },
    {
      id: "control-5",
      type: "multiple-choice",
      question: "Which of the following is wrong in Python?",
      options: ["if x == 5:", "if x = 5:", "if x != 5:", "if x > 5:"],
      correctAnswer: 1,
      explanation: "= is assignment, not comparison. Use ==.",
    },
    {
      id: "control-6",
      type: "multiple-choice",
      question: "What will this code print?\n\nscore = 75\nif score >= 90:\n    print(\"Grade A\")\nelif score >= 60:\n    print(\"Grade B\")\nelse:\n    print(\"Grade C\")",
      options: ["Grade A", "Grade B", "Grade C", "Error"],
      correctAnswer: 1,
      explanation: "75 ≥ 60, but not ≥ 90, so Grade B.",
    },
    {
      id: "control-7",
      type: "multiple-choice",
      question: "Which keyword is used to handle “otherwise” condition?",
      options: ["elseif", "other", "else", "default"],
      correctAnswer: 2,
      explanation: "else is used when no condition matches.",
    },
    {
      id: "loops-17",
      type: "multiple-choice",
      question: "What is the output?\n\nfor i in range(1, 5):\n    if i == 3:\n        break\n    print(i)",
      options: ["1 2 3 4", "1 2", "1 2 3", "Error"],
      correctAnswer: 1,
      explanation: "Loop stops when i = 3.",
    },
    {
      id: "loops-18",
      type: "multiple-choice",
      question: "What is the output?\n\nfor i in range(1, 5):\n    if i == 3:\n        continue\n    print(i)",
      options: ["1 2 3 4", "1 2 4", "1 2", "Error"],
      correctAnswer: 1,
      explanation: "continue skips 3.",
    },
    {
      id: "loops-19",
      type: "multiple-choice",
      question: "Which keyword skips current iteration but continues loop?",
      options: ["skip", "continue", "break", "next"],
      correctAnswer: 1,
      explanation: "continue skips only current step.",
    },
    {
      id: "loops-20",
      type: "multiple-choice",
      question: "Which keyword completely exits a loop?",
      options: ["stop", "break", "continue", "exit()"],
      correctAnswer: 1,
      explanation: "break ends the loop fully.",
    },
    {
      id: "strings-1",
      type: "multiple-choice",
      question: "Which data type is used for text in Python?",
      options: ["int", "str", "text", "char"],
      correctAnswer: 1,
      explanation: "Strings in Python are represented using str.",
    },
    {
      id: "strings-2",
      type: "multiple-choice",
      question: "What is the index of the first character in a string?",
      options: ["0", "1", "-1", "2"],
      correctAnswer: 0,
      explanation: "Indexing starts from 0.",
    },
    {
      id: "strings-3",
      type: "multiple-choice",
      question: "What is the output?\n\nword = \"Python\"\nprint(word[2])",
      options: ["P", "y", "t", "o"],
      correctAnswer: 2,
      explanation: "Index 2 = third character = 't'.",
    },
    {
      id: "strings-4",
      type: "multiple-choice",
      question: "What does word[1:4] print if word = 'Python'?",
      options: ["yth", "Pyt", "ytho", "t"],
      correctAnswer: 0,
      explanation: "Slice prints characters from index 1 to 3.",
    },
    {
      id: "strings-5",
      type: "multiple-choice",
      question: "What will this code print?\n\ntext = 'hello'\nprint(text.upper())",
      options: ["hello", "HELLO", "Error", "Hello"],
      correctAnswer: 1,
      explanation: ".upper() converts to capital letters.",
    },
    {
      id: "strings-6",
      type: "multiple-choice",
      question: "Which method converts string into lowercase?",
      options: ["lower()", "down()", "tolower()", "small()"],
      correctAnswer: 0,
      explanation: "lower() makes all characters small.",
    },
    {
      id: "strings-7",
      type: "multiple-choice",
      question: "What is the output?\n\ntext = 'I like Maths'\nprint(text.replace('Maths', 'Science'))",
      options: ["I like Maths", "I like Science", "Science like I", "Error"],
      correctAnswer: 1,
      explanation: ".replace() replaces one word with another.",
    },
    {
      id: "strings-8",
      type: "multiple-choice",
      question: "What is the output?\n\nname = 'Arun'\nage = 16\nprint(f'My name is {name}, I am {age} years old')",
      options: ["My name is Arun, I am 16 years old", "My name is {name}, I am {age} years old", "Error", "My name is Arun, I am age years old"],
      correctAnswer: 0,
      explanation: "f-string allows inserting variables.",
    },
    {
      id: "strings-9",
      type: "multiple-choice",
      question: "What symbol is used for multiline strings?",
      options: ["' '", '" "', '""" """', '<< >>'],
      correctAnswer: 2,
      explanation: "Triple quotes (\"\"\") are used.",
    },
    {
      id: "strings-10",
      type: "multiple-choice",
      question: "What is the output?\n\nmsg = 'Python'\nprint(msg[-1])",
      options: ["P", "n", "o", "Error"],
      correctAnswer: 1,
      explanation: "Negative index -1 gives last character.",
    },
  ],
  "data-structures": [
    {
      id: "lists-1",
      type: "multiple-choice",
      question: "Which is the correct way to create a list?",
      options: ["list = {1,2,3}", "list = [1,2,3]", "list = (1,2,3)", "list = <1,2,3>"],
      correctAnswer: 1,
      explanation: "Lists use square brackets [].",
    },
    {
      id: "lists-2",
      type: "multiple-choice",
      question: "What is the index of 'banana' in this list?\n\nfruits = ['apple', 'banana', 'mango']",
      options: ["0", "1", "2", "3"],
      correctAnswer: 1,
      explanation: "Indexing starts at 0 → apple(0), banana(1), mango(2).",
    },
    {
      id: "lists-3",
      type: "multiple-choice",
      question: "What is the output?\n\nfruits = ['apple', 'banana', 'mango']\nprint(fruits[1:3])",
      options: ["['apple', 'banana']", "['banana', 'mango']", "['apple', 'mango']", "['mango']"],
      correctAnswer: 1,
      explanation: "Slice 1:3 = items at index 1 and 2.",
    },
    {
      id: "lists-4",
      type: "multiple-choice",
      question: "Which method adds an item to the end of a list?",
      options: ["insert()", "append()", "add()", "push()"],
      correctAnswer: 1,
      explanation: ".append() adds item at the end.",
    },
    {
      id: "lists-5",
      type: "multiple-choice",
      question: "What is the output?\n\nfruits = ['apple', 'banana']\nfruits.insert(1, 'orange')\nprint(fruits)",
      options: ["['apple', 'banana', 'orange']", "['orange', 'apple', 'banana']", "['apple', 'orange', 'banana']", "Error"],
      correctAnswer: 2,
      explanation: "insert(1, value) adds at index 1.",
    },
    {
      id: "lists-6",
      type: "multiple-choice",
      question: "Which method removes the last element from a list?",
      options: ["delete()", "pop()", "remove()", "cut()"],
      correctAnswer: 1,
      explanation: ".pop() removes last element (or specific index).",
    },
    {
      id: "lists-7",
      type: "multiple-choice",
      question: "Which method removes a specific item by name?",
      options: ["pop()", "remove()", "delete()", "cut()"],
      correctAnswer: 1,
      explanation: ".remove('value') removes that item.",
    },
    {
      id: "lists-8",
      type: "multiple-choice",
      question: "What is the output?\n\nnums = [1, 2, 3]\ncopy_nums = nums.copy()\nnums.append(4)\nprint(copy_nums)",
      options: ["[1, 2, 3]", "[1, 2, 3, 4]", "[]", "Error"],
      correctAnswer: 0,
      explanation: ".copy() makes a new list, not affected by changes.",
    },
    {
      id: "lists-9",
      type: "multiple-choice",
      question: "Which method is used to reverse a list?",
      options: ["reverse()", "invert()", "flip()", "rev()"],
      correctAnswer: 0,
      explanation: ".reverse() reverses the order.",
    },
    {
      id: "lists-10",
      type: "multiple-choice",
      question: "What is the output?\n\nlist1 = ['a', 'b', 'c']\nlist1.reverse()\nprint(list1)",
      options: ["['a', 'b', 'c']", "['c', 'b', 'a']", "['abc']", "Error"],
      correctAnswer: 1,
      explanation: ".reverse() changes the list in place.",
    },
    {
      id: "tuple-1",
      type: "multiple-choice",
      question: "How do you create a tuple in Python?",
      options: ["tuple = [1,2,3]", "tuple = (1,2,3)", "tuple = {1,2,3}", "tuple = <1,2,3>"],
      correctAnswer: 1,
      explanation: "Tuples use round brackets ().",
    },
    {
      id: "tuple-2",
      type: "multiple-choice",
      question: "Are tuples mutable in Python?",
      options: ["Yes", "No", "Only with numbers", "Only with strings"],
      correctAnswer: 1,
      explanation: "Tuples are immutable (cannot be changed).",
    },
    {
      id: "tuple-3",
      type: "multiple-choice",
      question: "Which method counts occurrences in a tuple?",
      options: ["count()", "find()", "index()", "sum()"],
      correctAnswer: 0,
      explanation: "count() returns number of times a value appears.",
    },
    {
      id: "set-1",
      type: "multiple-choice",
      question: "How do you create a set in Python?",
      options: ["set = [1,2,3]", "set = (1,2,3)", "set = {1,2,3}", "set = <1,2,3>"],
      correctAnswer: 2,
      explanation: "Sets use curly braces {}.",
    },
    {
      id: "set-2",
      type: "multiple-choice",
      question: "Which method adds an item to a set?",
      options: ["add()", "append()", "insert()", "push()"],
      correctAnswer: 0,
      explanation: "add() adds an item to a set.",
    },
    {
      id: "set-3",
      type: "multiple-choice",
      question: "What is the output of {1,2,3} | {3,4,5}?",
      options: ["{1,2,3,4,5}", "{3}", "{1,2,3}", "Error"],
      correctAnswer: 0,
      explanation: "| is union, combines all unique elements.",
    },
    {
      id: "dict-1",
      type: "multiple-choice",
      question: "How do you access a value by key in a dictionary?",
      options: ["dict.key", "dict[key]", "dict->key", "dict.getkey()"],
      correctAnswer: 1,
      explanation: "Use dict[key] to access value by key.",
    },
    {
      id: "dict-2",
      type: "multiple-choice",
      question: "Which method removes a key-value pair from a dictionary?",
      options: ["remove()", "delete()", "pop()", "discard()"],
      correctAnswer: 2,
      explanation: "pop(key) removes the key-value pair.",
    },
    {
      id: "dict-3",
      type: "multiple-choice",
      question: "What is the output of list({'a':1, 'b':2}.keys())?",
      options: ["['a', 'b']", "['1', '2']", "['a', 'b', '1', '2']", "Error"],
      correctAnswer: 0,
      explanation: "keys() returns all keys in a dictionary.",
    },
    {
      id: "tuple-4",
      type: "multiple-choice",
      question: "Which brackets are used to create a tuple in Python?",
      options: ["[]", "()", "{}", "<>"] ,
      correctAnswer: 1,
      explanation: "Tuples use round brackets ().",
    },
    {
      id: "tuple-5",
      type: "multiple-choice",
      question: "What is the output?\n\ncolors = ('red', 'blue', 'green')\nprint(colors[1])",
      options: ["red", "blue", "green", "Error"],
      correctAnswer: 1,
      explanation: "Index 1 = second element.",
    },
    {
      id: "tuple-6",
      type: "multiple-choice",
      question: "Can we change values inside a tuple directly?",
      options: ["Yes", "No", "Only numbers", "Sometimes"],
      correctAnswer: 1,
      explanation: "Tuples are immutable (cannot be changed).",
    },
    {
      id: "tuple-7",
      type: "multiple-choice",
      question: "What will this code print?\n\nnums = (1, 2, 2, 3)\nprint(nums.count(2))",
      options: ["1", "2", "3", "Error"],
      correctAnswer: 1,
      explanation: ".count(2) returns how many times 2 appears.",
    },
    {
      id: "tuple-8",
      type: "multiple-choice",
      question: "What will this code print?\n\nnums = (1, 2, 3, 4)\nprint(nums.index(3))",
      options: ["2", "3", "1", "Error"],
      correctAnswer: 0,
      explanation: "Index of 3 is position 2.",
    },
    {
      id: "set-4",
      type: "multiple-choice",
      question: "Which brackets are used for sets in Python?",
      options: ["[]", "{}", "()", "<>"] ,
      correctAnswer: 1,
      explanation: "Sets use curly brackets {}.",
    },
    {
      id: "set-5",
      type: "multiple-choice",
      question: "What is the output?\n\nnums = {1, 2, 2, 3}\nprint(nums)",
      options: ["{1, 2, 2, 3}", "{1, 2, 3}", "[1, 2, 3]", "Error"],
      correctAnswer: 1,
      explanation: "Sets remove duplicates automatically.",
    },
    {
      id: "set-6",
      type: "multiple-choice",
      question: "Which method adds an item to a set?",
      options: ["insert()", "append()", "add()", "push()"],
      correctAnswer: 2,
      explanation: "add() is used to insert into sets.",
    },
    {
      id: "set-7",
      type: "multiple-choice",
      question: "Which method removes an item from a set?",
      options: ["remove()", "delete()", "pop()", "discard()"],
      correctAnswer: 0,
      explanation: ".remove() deletes specific item (if present).",
    },
    {
      id: "set-8",
      type: "multiple-choice",
      question: "What is the result of:\n\nA = {1, 2, 3}\nB = {3, 4}\nprint(A.union(B))",
      options: ["{1, 2, 3, 4}", "{3}", "{1, 2}", "Error"],
      correctAnswer: 0,
      explanation: "Union joins both sets.",
    },
    {
      id: "set-9",
      type: "multiple-choice",
      question: "What is the result of:\n\nA = {1, 2, 3}\nB = {3, 4}\nprint(A.intersection(B))",
      options: ["{1, 2, 3, 4}", "{3}", "{1, 2}", "Error"],
      correctAnswer: 1,
      explanation: "Intersection gives common items.",
    },
    {
      id: "dict-4",
      type: "multiple-choice",
      question: "Which of the following is correct dictionary syntax?",
      options: ["student = {'name': 'Arun', 'age': 16}", "student = {'name', 'Arun', 'age', 16}", "student = ['name': 'Arun', 'age': 16]", "student = ('name': 'Arun', 'age': 16)"],
      correctAnswer: 0,
      explanation: "Dictionary uses key:value pairs inside {}.",
    },
    {
      id: "dict-5",
      type: "multiple-choice",
      question: "How do you access the value of 'name'?\n\nstudent = {'name': 'Arun', 'age': 16}",
      options: ["student.name", "student['name']", "student.get['name']", "student('name')"],
      correctAnswer: 1,
      explanation: "Access with student['name'].",
    },
    {
      id: "dict-6",
      type: "multiple-choice",
      question: "What will this code print?\n\nstudent = {'name': 'Arun', 'age': 16}\nprint(student.get('age'))",
      options: ["name", "Arun", "16", "Error"],
      correctAnswer: 2,
      explanation: ".get('age') returns 16.",
    },
    {
      id: "dict-7",
      type: "multiple-choice",
      question: "Which method is used to remove a key from dictionary?",
      options: ["remove()", "pop()", "delete()", "discard()"],
      correctAnswer: 1,
      explanation: ".pop('key') removes that entry.",
    },
    {
      id: "dict-8",
      type: "multiple-choice",
      question: "What is the output?\n\nstudent = {'name': 'Arun', 'age': 16}\nstudent['age'] = 17\nprint(student)",
      options: ["{'name': 'Arun', 'age': 16}", "{'name': 'Arun', 'age': 17}", "{'name': 'Arun'}", "Error"],
      correctAnswer: 1,
      explanation: "Updating value changes it to 17.",
    },
    {
      id: "dict-9",
      type: "multiple-choice",
      question: "Which method copies a dictionary?",
      options: ["copy()", "duplicate()", "clone()", "replicate()"],
      correctAnswer: 0,
      explanation: ".copy() makes a new dictionary.",
    },
  ],
  "numpy-pandas": [
    {
      id: "numpy-1",
      type: "multiple-choice",
      question: "What is NumPy primarily used for?",
      options: ["Web development", "Numerical computing and arrays", "Database management", "GUI development"],
      correctAnswer: 1,
      explanation: "NumPy is primarily used for numerical computing and working with arrays.",
    },
    {
      id: "numpy-2",
      type: "multiple-choice",
      question: "What is Pandas primarily used for?",
      options: ["Image processing", "Data manipulation and analysis", "Machine learning", "Web scraping"],
      correctAnswer: 1,
      explanation: "Pandas is primarily used for data manipulation and analysis.",
    },
    {
      id: "numpy-3",
      type: "multiple-choice",
      question: "Which function creates a NumPy array?",
      options: ["np.list()", "np.array()", "np.arr()", "np.make()"],
      correctAnswer: 1,
      explanation: "np.array() is used.",
    },
    {
      id: "numpy-4",
      type: "multiple-choice",
      question: "What is the output?\n\nimport numpy as np\narr = np.array([1, 2, 3])\nprint(arr.mean())",
      options: ["2.0", "3.0", "6", "Error"],
      correctAnswer: 0,
      explanation: "Mean = (1+2+3)/3 = 2.0.",
    },
    {
      id: "pandas-1",
      type: "multiple-choice",
      question: "Which Pandas object is used for tabular data (like Excel)?",
      options: ["Series", "DataFrame", "Array", "DictFrame"],
      correctAnswer: 1,
      explanation: "DataFrame stores rows & columns.",
    },
  ],
}
